services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    container_name: mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: dat
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
