apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: tangthiendat/kub-data-demo:1
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
