apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: tangthiendat/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: "10.98.122.94"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
